name: CI

on:
  push:
    branches: [ staging, trying, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target:
          - thumbv6m-none-eabi
          - thumbv7m-none-eabi
          - thumbv7em-none-eabi
          - thumbv7em-none-eabihf
          - thumbv8m.base-none-eabi
          - thumbv8m.main-none-eabi
          - thumbv8m.main-none-eabihf
        rust:
          - 1.53.0
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          components: clippy
          override: true
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
      - uses: actions-rs/clippy-check@v1
        with:
          args: "--target ${{ matrix.target }}"
          token: ${{ secrets.GITHUB_TOKEN }}
